name: Terraform Apply

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-oidc-role
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Test AWS Credentials
        run: aws sts get-caller-identity 

      - name: Download tfvars file from S3
        run: aws s3 cp s3://my-terraform-threat-modelling-bucket/terraform.tfvars terraform/terraform.tfvars

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform


      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve terraform/tfplan
        working-directory: terraform

      - name: Summary
        run: echo "### 🚀 Terraform Apply Completed" >> $GITHUB_STEP_SUMMARY
